### ISSUE TITLE
Support inserting custom attributes

### ISSUE THREAD

**Issue by bravo-kernel** [alt3/sequelize-to-json-schemas#15]
Think through but we need a generic solution for e.g. the following cases:

- a `users/authenticate` endpoint using the `user`  model but with a virtual `strategy` attribute (not in the database and/or sequelize)

**Comment by wolfgangwalther** [comment]
Not sure whether thats the right way to go. I wouldn't expect to POST a `user` model on `users/authenticate` but rather a `authentication` model - whatever that is. Probably not defined in sequelize - but not every endpoint needs to be derived automatically from a sequelize model. Endpoints that are not related to sequelize should not be part of `sequelize-to-json-schemas`.

If it was indeed the correct model, then I would expect to add a VIRTUAL field on the model to add it to the docs..

**Comment by bravo-kernel** [comment]
I have looked at VIRTUAL myself since creating this ticket and that might be the best solution. I will still need to test it though, will probably happen this weekend. If it suffices, I will close this ticket. 

Thanks for thinking along here 👍

**Comment by bravo-kernel** [comment]
And... very good point about the question if it should/should not be in `sequelize-to-json-schemas`. I never thought about it but now that you mentioned it.. my `authenticate` endpoint should probably just be inserted, totally separated from `sequelize-to-json-schemas`. 💯

**Comment by bravo-kernel** [comment]
Closing as per discussion above to prevent confusion for future visitors.
