### ISSUE TITLE
Integration with FeathersJS

### ISSUE THREAD

**Issue by bravo-kernel** [alt3/sequelize-to-json-schemas#17]
Follow these steps to automatically generate model schemas for [feathers-swagger](https://github.com/feathersjs-ecosystem/feathers-swagger).

1. Create a `src/sequelize-to-json-schemas.js` schema configuration file:

 ```js
const {
  JsonSchemaManager,
  OpenApi3Strategy,
} = require('@alt3/sequelize-to-json-schemas');

module.exports = function init(app) {
  const schemaManager = new JsonSchemaManager({
    baseUri: 'https://api.example.com',
    absolutePaths: true,
  });

  const openApi3Strategy = new OpenApi3Strategy();

  app.set('jsonSchemaManager', schemaManager);
  app.set('openApi3Strategy', openApi3Strategy);
};
```

2. Make sure your `src/app.js` contains the following sections:

```js
// Configure sequelize-to-json-schemas
app.configure(sequelizeToJsonSchemas);

// Set up feathers-swagger for OpenAPI
app.configure(
  swagger({
    openApiVersion: 3,
    uiIndex: true,
    docsPath: '/docs',
    docsJsonPath: '/docs/schema',
    specs: {
      info: {
        title: 'Your title',
        description: 'Your description',
        version: '0.0.1',
      },
    },
    defaults: {
      schemasGenerator(service, model, modelName) {
        return {
          [model]: service.model,
          [`${model}_list`]: {
            title: `${modelName} list`,
            type: 'array',
            items: { $ref: `#/components/schemas/${model}` },
          },
        };
      },
    },
  }),
);
```

3. Now add the following to your service definitions (e.g. `src/projects/services.js`) which will:

- automatically generate the model schema using your Sequelize model definition
- append the generated model schema to the feathers-swagger schema

```js
  // generate OpenAPI 3.0 model schema as required by feathers-swagger
  service.model = app
    .get('jsonSchemaManager')
    .generate(Model, app.get('openApi3Strategy', { options }));
```

4. Refer to this repo's readme for the availabe configuration options

**Comment by justraman** [comment]
.generate(service.service.options.Model, app.get('openApi3Strategy'), service.options.Model.options.jsonSchema);
                                          ^
TypeError: Cannot read property 'options' of undefined

Getting this issue when i config swagger before calling services.

Issue disappear when i configure swagger after services, but at that time docs have no operations as you can see in screenshot 
![Screenshot from 2020-05-07 13-01-22](https://user-images.githubusercontent.com/25192346/81266722-e61bd580-9062-11ea-8d24-8c456484e98a.png)

**Comment by jackywxd** [comment]
@justraman I had the same issue. It seems that was caused by the /auth (authentication) service. Feathers internal authentication service doesn't have options and Model properties. The workaround is simple, just check the existence of the properties before using them:
 
if (service.options && service.options.Model) {
  const modelSchema = app
            .get("jsonSchemaManager")
            .generate(
              service.options.Model,
              app.get("openApi3Strategy"),
              service.options.Model.options.jsonSchema
            );

          return {
            [model]: modelSchema,
            [`${model}_list`]: {
              title: `${modelName} list`,
              type: "array",
              items: { $ref: `#/components/schemas/${model}` },
            },
          };
}

**Comment by Kelvince01** [comment]
> 

This works for me
