### ISSUE TITLE
JSON columns do not produce valid OpenAPI v3

### ISSUE THREAD

**Issue by robbyphillips** [alt3/sequelize-to-json-schemas#21]
Currently, the JSON column type is mapped to the internal `ANY` type, an array of `['object', 'string', ...]`, which fails the OpenAPI validation.

Since it is true that a JSON column really could be any of those types, I think the simplest solution might be to add a column type override option to the column's `jsonSchema` settings object, potentially accepting a whole schema object with its own `properties` and `required` attributes.

**Comment by bravo-kernel** [comment]
You might be very right, I took this solution from another lib but never used the type myself which is also the reason it is not yet tested in https://github.com/alt3/sequelize-to-json-schemas/blob/master/test/models/user.js. 

If you can come up with a viable solution I am more than willing to merge it in, as long as the generated json keeps passing the validator.

**Comment by robbyphillips** [comment]
PR submitted over here: #22
