### ISSUE TITLE
Should null be added to list of valid types when defaultValue is null and allowNull is not defined

### ISSUE THREAD

**Issue by brayden-bcgsc** [alt3/sequelize-to-json-schemas#54]
I'm not sure if this is an issue or if the code is acting as expected. When your Sequelize model has a property that has defaultValue set to null and allowNull is not defined, in the generated schema, should null be added to the list of valid types for that property? Currently it is not. I guess the question is, if your defaultValue is null does that necessarily mean you accept null as input for that property in the schema?

**Comment by bravo-kernel** [comment]
Good observation. With questions like I always look at the code from our colleague libraries as well (e.g. sequelize-json-schema). In their index. js I see the following:

```js
  // Add null? (Sequelize allowNull defaults to true)
  if (att.allowNull !== false) schema = _addType(schema, 'null');
```

Makes sense to me and seems like the answer to your question. If sequelize indeed allows null by default we should probably make this explicit in the schemas by default. Do you agree?

**Comment by brayden-bcgsc** [comment]
Yeah, I agree. I just wanted to verify with you and make sure there is not a specific reason it works the way it does.

**Comment by bravo-kernel** [comment]
Feel free to PR, otherwise I will put in a change this weekend, this looks like it will be a non-breaking change.

**Comment by bravo-kernel** [comment]
Closing through #55 and #58
