### ISSUE TITLE
feathers v4  integration

### ISSUE THREAD

**Issue by justraman** [alt3/sequelize-to-json-schemas#68]
.generate(service.service.options.Model, app.get('openApi3Strategy'), service.options.Model.options.jsonSchema);
                                          ^
TypeError: Cannot read property 'options' of undefined

Getting this issue when i config swagger before calling services.

Issue disappear when i configure swagger after services, but at that time docs have no operations as you can see in screenshot 
![Screenshot from 2020-05-07 13-01-22](https://user-images.githubusercontent.com/25192346/81266722-e61bd580-9062-11ea-8d24-8c456484e98a.png)

_Originally posted by @justraman in https://github.com/alt3/sequelize-to-json-schemas/issues/17#issuecomment-625083004_

**Comment by justraman** [comment]
[SOLVED]
 I  was calling app.configure(swagger({..}))
 before app.configure(authentication);

solved by calling app.configure(swagger({..})) just after app.configure(authentication);

**Comment by justraman** [comment]
Thank You @bravo-kernel and @team for making such a great library.

**Comment by bravo-kernel** [comment]
You're welcome. Please ⭐ if you like.
