### ISSUE TITLE
Bad comment in schema-manager

### ISSUE THREAD

**Issue by Ismonh** [alt3/sequelize-to-json-schemas#85]
![image](https://user-images.githubusercontent.com/24719936/140094905-1bbf0fbc-7011-450c-9c0a-ec947c9ebfbc.png)

**Comment by FlorianGG** [comment]
Where is the respect?

**Comment by FlorianGG** [comment]
It seems that @Ismonh wants to say that `options.disableComments` is a boolean (not a string) and his default value is true (not false). You can also use these syntax `this._verifyOptions({...defaultOptions, ...options})`

**Comment by bravo-kernel** [comment]
Thank you for reporting and.. for explaining the screenshot ❤️
